# Generated by Django 5.1.1 on 2024-09-18 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inaEthe', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='inaEthe.category'),
        ),
    ]
